name: Verify

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Gradle Build
      uses: docker://gcr.io/cloud-builders/gradle
      with:
        args: build
